{
    "name": "Mobile Manufacturing & IMEI Quality Management",
    "summary": "End-to-end mobile production, raw material QC, IMEI, rework, barcode QC and box packaging",
    "version": "19.0.1.0.0",
    "category": "Manufacturing/Manufacturing",
    "author": "Kazi Md Saydunnobi",
    "website": "https://zencore.com.bd",
    "license": "LGPL-3",
    "depends": [
        "web",
        "mail",
        "mrp",
        "stock",
        "barcodes",
    ],
    "data": [
        "security/mobile_manufacturing_security.xml",
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "views/mobile_config_views.xml",
        "views/raw_receipt_views.xml",
        "views/raw_qc_views.xml",
        "views/material_requisition_views.xml",
        "views/mrp_production_views.xml",
        "views/production_qc_views.xml",
        "views/mobile_device_views.xml",
        "views/device_qc_views.xml",
        "views/rework_views.xml",
        "views/packaging_views.xml",
        "views/imei_wizard_views.xml",
        "views/qc_scanner_views.xml",
        "report/packaging_report_templates.xml",
        "report/packaging_report.xml",
        "views/mobile_manufacturing_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "mobile_manufacturing_management/static/src/scss/mobile_manufacturing.scss",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
