{
    'name': 'Newspaper Advertisement Management',
    'version': '19.0.1.0',
    'category': 'Sales',
    'summary': 'Manage Newspaper Ads, Pages, Pricing and Orders',
    'author': 'Kazi Md Saydunnobi',
    'depends': ['base', 'sale_management', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/newspaper_availability_wizard_views.xml',
        'data/newspaper_data.xml',
        'views/newspaper_menus.xml',
        'views/newspaper_page_views.xml',
        'views/newspaper_ad_size_views.xml',
        'views/newspaper_ad_position_views.xml',
        'views/newspaper_customer_type_views.xml',
        'views/newspaper_pricelist_views.xml',
        'views/newspaper_misc_views.xml',
        'views/newspaper_ad_order_views.xml',
        'views/res_partner_views.xml',
    ],
    'installable': True,
    'application': True,
    'icon': 'static/description/icon.png',
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'description': """<p>Manage newspaper advertisements, pages, pricing, and orders with a sleek Odoo interface.</p>""",
}
